services:
  - type: web
    name: penai-morehouse-chatbot
    env: python
    buildCommand: >
      pip install --upgrade pip setuptools wheel &&
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPL_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9


