# Auto-generated from metadata.pkl – do not edit by hand.
URL_MAPPING = {
  "Admissions": "https://www.cheltenhamcollege.org/admissions/",
  "Anti-Bullying Policy": "https://www.cheltenhamcollege.org/wp-content/uploads/2025/02/Modern-Slavery-Statement.pdf",
  "Behaviour Policy": "https://www.cheltenhamcollege.org/wp-content/uploads/2025/02/Modern-Slavery-Statement.pdf",
  "Boarding": "https://www.cheltenhamcollege.org/college/houses/",
  "Co-curricular": "https://www.cheltenhamcollege.org/college/co-curricular/",
  "Complaints Policy": "https://www.cheltenhamcollege.org/wp-content/uploads/2025/02/Modern-Slavery-Statement.pdf",
  "Contact": "https://www.cheltenhamcollege.org/contact-us/",
  "Enquiry": "https://www.cheltenhamcollege.org/contact-us/",
  "Fees": "https://www.cheltenhamcollege.org/admissions/fees/",
  "Homepage": "https://www.cheltenhamcollege.org/",
  "ISI Report": "https://www.cheltenhamcollege.org/wp-content/uploads/2025/02/Modern-Slavery-Statement.pdf",
  "Learning Support": "https://www.cheltenhamcollege.org/health-promotion/",
  "Music": "https://www.cheltenhamcollege.org/individual-music-lessons/",
  "Open Events": "https://www.cheltenhamcollege.org/admissions/visit-us/",
  "Pastoral Care": "https://www.cheltenhamcollege.org/college/health-wellbeing/",
  "Policies": "https://www.cheltenhamcollege.org/about-us/aims-policies/",
  "Privacy Policy": "https://www.cheltenhamcollege.org/privacy-terms/",
  "Results": "https://www.cheltenhamcollege.org/college/2025-results/",
  "Safeguarding Policy": "https://www.cheltenhamcollege.org/wp-content/uploads/2025/02/Modern-Slavery-Statement.pdf",
  "Scholarships and Bursaries": "https://www.cheltenhamcollege.org/scholarships-key-dates/",
  "Sixth Form": "https://www.cheltenhamcollege.org/college/sixth-form/",
  "Sport": "https://www.cheltenhamcollege.org/college/sport/",
  "Subjects": "https://www.cheltenhamcollege.org/college/lower-college-curriculum/",
  "Term Dates": "https://www.cheltenhamcollege.org/key-information-for-parents/term-dates/",
  "Transport": "https://www.cheltenhamcollege.org/key-information-for-parents/bus-service/",
  "Uniform": "https://www.cheltenhamcollege.org/key-information-for-parents/uniform/",
}
